version: '2.2'

services:
  client:
    restart: on-failure
    expose:
      - 80
    ports:
      - 80:80
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: npm run dev
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - local

  mongo:
    image: mongo
    restart: on-failure
    volumes:
      - apiDB:/data/db
    networks:
      - local

volumes:
  apiDB:

networks:
  local:
